# Generated by Django 3.0.3 on 2020-05-31 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes', '0003_auto_20200531_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlike',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userlike',
            name='liked_users',
        ),
        migrations.AddField(
            model_name='userlike',
            name='liked_users',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='liked_users', serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
