# Generated by Django 3.0.3 on 2020-06-01 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0009_auto_20200601_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlike',
            old_name='userr',
            new_name='user',
        ),
    ]
